Feature/white voting
EGC-zambrano/decide-part-zambrano pull request #26
Opened 2023-11-14 21:35 UTC by samrodman

This feature allows the decide system to create a default option equal to a blank vote whenever we create a new question, even when the question's options are empty.

2023-11-15 20:23 UTC, marnunrey2 approved these changes
Everything looks fine and working

2023-12-14 11:52 UTC, samrodman commented
This feature and its branch was originally created and started by user FelixoGudiel, but after some time he moved to another feature and I continued this one. I also implemented the tests like originally planned.

2023-12-14 11:56 UTC, AntonioRodriguezRuiz commented
> This feature and its branch was originally created and started by user FelixoGudiel, but after some time he moved to another feature and I continued this one. I also implemented the tests like originally planned.

I understand, it was not ideal since we decided that the tests would be done by a different person from the one implementing the functionality but I get the situation and it's no problem. All good :+1:

2023-12-14 12:05 UTC, AntonioRodriguezRuiz requested changes

2023-12-14 12:05 UTC, AntonioRodriguezRuiz commented on decide/voting/models.py
> +        print(self.tally)
Please remove this print statement

2023-12-14 12:26 UTC, AntonioRodriguezRuiz requested changes
I found that if you try to create a white voting from the django admin panel and assign value 1 to the first voting, which should be the defaiult. The resulting question ends up like this:
![image](https://github.com/EGC-zambrano/decide-part-zambrano/assets/73228905/ad205313-1000-4554-ab00-2a64c735fed9)

Which could be a problem on the tally. I suggest that you make the question number the last

2023-12-14 19:31 UTC, samrodman commented
changes have been implemented. should work fine now, thanks.

2023-12-14 19:40 UTC, merged