Registro de usuarios
EGC-zambrano/decide-part-zambrano pull request #4
Opened 2023-11-03 13:17 UTC by marnunrey2

Se ha creado el registro de usuarios de tal forma que al hacer click en el link de "Registrarse" en el homepage te redirige a una página con el mismo estilo que el home. En el puedes encontrar un registration form tipico de Django donde es necesario completar todos los campos o, de lo contrario, saltaría un mensaje pidiendo al usuario que complete el campo que ha dejado sin rellenar. 
También se ha añadido funcionalidad para comprobar que la contraseña cumple con los requisitos típicos (número mínimo de caracteres, que no coincida con el usuario, nombre, etc) y que se igual a la contraseña de confirmación. 
Además, se ha añadido código en JavaScript para seleccionar por defecto que empiece completando el formulario por el nombre y se ha modificado el base.html para que el h1 que contiene el string "Decide" funcione como un link en cualquier página que al hacer click vuelva al homepage.

2023-11-03 13:23 UTC, marnunrey2 commented
test: queda pendiente realizar los tests por parte de uno de mis compañeros

2023-11-11 11:21 UTC, AntonioRodriguezRuiz requested changes
This is really good, nice job! I just need one more selenium test that is missing

2023-11-11 11:21 UTC, AntonioRodriguezRuiz commented on decide/authentication/test-selenium.py
> +        self.assertTrue(self.driver.title == "Decide | Registration")
This test does not send a request and get an error back, it simply rejects the form contents before sending it to the backend. Please add another test with, for example, a password that is too short to check that everything works as intended

2023-11-11 13:04 UTC, TunixR approved these changes

2023-11-11 13:15 UTC, Marchabar approved these changes
Good Job!

2023-11-11 18:43 UTC, merged