Feature/email after registration
EGC-zambrano/decide-part-zambrano pull request #45
Opened 2023-12-13 17:11 UTC by FelixoGudiel

For the Sendgrid email system to work, sendgrid must be installed. To do so:

```
pip install -r requirements.txt
python decide/manage.py makemigrations
python decide/manage.py migrate
```

In your .env add the following (ask FelixoGudiel for the values of the variables and do not share them):

```
SENDGRID_API_KEY=sendgrid_key
```

If you did all of this correctly, it should work.

The main purpose of this feature is to authenticate the user. For this, once the user registers, an email is sent to the address given. The email has a link to a page where the user will be marked as authenticated. If any non authenticated user tries to vote, he will be redirected to the main page and told to verify their account in order to vote.

2023-12-14 12:12 UTC, Marchabar requested changes
The functionality is good, but the styles of the notifications should be much more visible and disappear after some seconds (like a pop-up for example). Also when the user is not logged in and access the email url, the message should say something like you are not logged in or something like that.

2023-12-14 12:39 UTC, Marchabar requested changes

2023-12-14 12:39 UTC, Marchabar commented on decide/booth/test-selenium.py
review this test, why are you guys commenting all this code

2023-12-14 16:41 UTC, FelixoGudiel commented on decide/booth/test-selenium.py
This was commented because the functionality was interfiering with previously made tests, so they were commented until we had time to update them. Now it is uncommented and working!

2023-12-14 16:45 UTC, FelixoGudiel commented
Thanks for yor insights, the message is now outputted through a popup. Also the test has been fixed. If you find any other incongruence, tell me!

2023-12-14 17:16 UTC, Marchabar requested changes
Improve message styles matching the rest of the theme, and check booth test is not passing

2023-12-14 18:04 UTC, FelixoGudiel commented
This is the current message style, if you think about any other improvement dont doubt to contact me 
![image](https://github.com/EGC-zambrano/decide-part-zambrano/assets/73229175/e1c3bd5e-5134-42c9-8215-2ae5af89463e)

2023-12-14 19:18 UTC, Marchabar approved these changes
Everything runs fine. Good job!

2023-12-15 15:02 UTC, pabpercab1 commented
I've reviewed the email feature introduced in this pull request, and unfortunately, the feature is not working as expected. I've carried out all the steps you wrote above to test and it seems it is not working.

When an email is ready to be sent in the registration form, in this lines it happens an exception:

```
 sg = SendGridAPIClient(os.environ.get("SENDGRID_API_KEY"))
 sg.send(mailMessage)
```

This results in the following:

`Exception: HTTP Error 401: Unauthorized`

I have also asked another person to test this feature, but unfortunately, the result is the same, with the same exception.

2023-12-15 15:12 UTC, FelixoGudiel commented
Sorry, I gave you a dead API Key. I have now sent you the correct one. Please, try again.

2023-12-15 15:16 UTC, pabpercab1 approved these changes
The issue is solved. Now the functionality works perfectly and the tests work. Good job!

2023-12-15 16:27 UTC, merged